### ISSUE TITLE
SMACv2

### ISSUE THREAD

**Issue by balloch** [FLAIROx/JaxMARL#110]
Is there plans to integrate with [SMACv2](https://github.com/oxwhirl/smacv2) ? Is there a relationship between SMAX and SMACv2 as far as you know?

**Comment by amacrutherford** [comment]
Hey! SMAX has the SMACv2 scenarios, as outlined [here](https://github.com/FLAIROx/JaxMARL/tree/main/jaxmarl/environments/smax#scenarios). However, as outlined in Section 3.2 of our [technical report](https://arxiv.org/pdf/2311.10090), SMAX makes improvements to SMAC, meaning they are different environments. Due to the improvements made, we suggest using SMAX over SMACv2.

**Comment by balloch** [comment]
great to know thanks!

**Comment by amacrutherford** [comment]
No worries, happy benchmarking!
